src/seal.rs
The unused type variable means that I have to do the following:
```
match filecoin_proofs_api::seal::seal_pre_commit_phase2::<PathBuf, PathBuf, ()>(
spcp1o,
c_str_to_pbuf(cache_dir_path),
c_str_to_pbuf(sealed_sector_path),
) {
```
and that is annoying. This PR eliminates that unused type variable.
=> type variable T isn't actually used, so can never be inferred at call site

src/post.rs, src/types.rs
The `generate_post` function has a parameter `replicas: &BTreeMap<SectorId, PrivateReplicaInfo>`. Each `PrivateReplicaInfo` has its own `RegisteredPoStProof`, and so the returned proofs need to indicate which `RegisteredPoStProof` was used to generate them.
=> feat: return the RegisteredPoStProof from generate_poast

src/lib.rs
The `Candidate` type moved modules on me.
I now import it from its new location.
=> Update to reflect new location of Candidate type

Cargo.toml, src/seal.rs
This PR adds support for `fauxrep` (fake sealing) as [implemented here](https://github.com/filecoin-project/rust-fil-proofs/pull/1194).
=> Support fauxrep.

src/seal.rs
This PR corrects an oversight in the first draft. When unrolling the `with_shape!` macro to insert appropriate shape type parameters based on sector size, the same type `SectorShape2KiB` was used for every sector size. Instead, use the correct shape for each sector size.
=> Use correct fauxrep shape type parameters per sector size.

release.toml
Also use "chore" as prefix for releases in case we start doing
automated changelogs.
=> chore: don't start a new dev version after a release

src/lib.rs
This way the FFI has access to specific storage proofs errors.
=> feat: export storage proofs errors

CHANGELOG.md, Cargo.toml, src/lib.rs, src/post.rs, src/types.rs
NOTE: This points to a branch on proofs, as it depends on https://github.com/filecoin-project/rust-fil-proofs/pull/1283
=> Expose distributed PoSt API from rust-fil-proofs

Cargo.toml, README.md, src/seal.rs
Allows usage of https://github.com/filecoin-project/rust-fil-proofs/pull/1401
=> Improve RAM usage during unseal

.circleci/config.yml, Cargo.toml
There is a dependency on `storage-proofs-porep`, but it isn't used anywhere in the source. I suspect that it was included in order to enable the `multicore-sdr` feature. But this feature can also be enabled through setting it on `filecoin-proofs-v1`, which will then set it on `storage-proofs-porep`. The same is true for the `cuda` and `opencl` features.
=> chore: remove the dependency on storage-proofs-porep

.circleci/config.yml
The CI was unnecessarily complex. It now uses also uses stock CircleCI images.
Due to that simplification there are cost saving while still having a similar total run time (300 vs 330s). From using around 5300 to 325 CircleCI credits.
=> chore: simplify CI

.circleci/config.yml, CHANGELOG.md, Cargo.toml, README.md
Now things are automatically built with CUDA enabled. If your system has a GPU that supports CUDA, it will be used. If there is only a GPU with OpenCL support, then it will fallback to it. If no GPU is available the CPU is used.
=> feat: enable CUDA by default

Cargo.toml
The `cuda-supraseal` feature enables faster C2.
=> feat: add cuda-supraseal feature

.circleci/config.yml
This PR migrated the macos builds in the repo to Apple Silicon executors since the Apple Intel ones are getting deprecated by January 2024. See https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718.
=> ci: switch macos builds to apple silicon

Cargo.toml
With the `fixed-rows-to-discard` feature not t_aux file will be written and the proving works without one. This is needed for using the SupraSeal PC2 implementation in Lotus.
=> feat: add fixed-rows-to-discard

.circleci/config.yml, Cargo.toml, src/registry.rs, src/seal.rs
This commit introduces new registered proof types in order to support ni-porep.
Also Rust >= 1.70 is needed due to the dependency on `home` v0.5.9.
=> feat: add support for Non-interactive PoRep

src/registry.rs, src/seal.rs
This commit fixes/updates new registered proof types in order to support ni-porep.
=> feat: fix proof name for Non-interactive PoRep

Cargo.toml, src/lib.rs, src/seal.rs
`storage_proofs_core` exports more commonly used types in newer released versions. This way we don't need to have a direct dependency on `bellperson` and `filecoin_hashers` anymore. This lowers the maintenance burden in case of new released. It also simplifies the feature handling, as we don't need to explicitly enable features on `filecoin_hashers` and `bellperson`.
=> refactor: use newly exported types

src/seal.rs
I found this change while browsing through open branches. It looks like I accidentally forgot to PR it back then (almost a year ago!). It's still worth merging today though.
---
The API docs were copy and pasted, but then not correctly adapted. Fix the wrong descriptions.
Also change the parameter naming to be more consistent.
=> docs: fix API docs

src/seal.rs
The `clear_layer_data` call was accidentally introduced with the Synthetic PoRep. The call does under the hood exactly what `clear_cache` is doing. It was already removed from the FFI via [PR 436], so that we can remove it here as well. This reduces the API surface, which is generally a good idea.
[PR 436]: https://github.com/filecoin-project/filecoin-ffi/pull/436
BREAKING CHANGE: `clear_layer_data` was removed, use `clear_cache` instead.
=> fix: remove clear_layer_data call

.github/workflows/ci.yml
Reverts filecoin-project/rust-filecoin-proofs-api#105
This is related to https://github.com/filecoin-project/github-mgmt/issues/132. This is a temporary revert. We need to first get back on hosted runners before getting on FilOz's self-hosted runners, because `self-hosted` tag is too permissive and would start matching any FilOz's runners as soon as I allow this repository to access them.
=> Revert "feat: test out self hosted runner"
